services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
