services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular_app_dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
