# Use a imagem base do Node
FROM node:22-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o package.json e instale as dependências
COPY package*.json ./
RUN npm install

# Copia o resto do código para a imagem (boa prática)
COPY . .

# Expõe a porta padrão do Angular
EXPOSE 4200

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "start", "--", "--poll=1000", "--host", "0.0.0.0"]
